### PR TITLE
remove unnecessary break in SDOs reference pane header

### PR DESCRIPTION
**Pull request by michaelficarra**
before:

image

after:

image

### CODE REVIEW

**Comment by bakkot** [comment]
I think this break is necessary for longer productions:
Screenshot 2024-06-17 at 7 37 45 AM

**Comment by michaelficarra** [comment]
Breaking doesn't prevent it from wrapping on a narrow-enough display. All it does is wrap unnecessarily on larger displays. We may be able to add some CSS to prefer breaking before the grammar alternative.

**Comment by michaelficarra** [comment]
Alternatively, we could just cut it off with an ellipsis when it doesn't fit:

image

**Comment by bakkot** [comment]
If you want to do that and _also_ have the linebreak, I'm ok with it I guess. But I don't want to make things less readable than they currently are. The screenshot I posted looks fine; dropping the linebreak and adding an ellipsis would be worse.

**Pull request closed without merging**
