### PR TITLE
Implement alternative license text

### PR DESCRIPTION
**Pull request by codehag**

### CODE REVIEW

**Comment by michaelficarra** [comment]
@codehag Can you link to the resolution or notes or something so I can confirm GA intent?

**Comment by syg** [comment]
@michaelficarra Does the GA even care about drafts per se?

**Comment by michaelficarra** [comment]
@syg I don't know. Also, in the reflector thread, I asked what notice should be included with the document submitted to the GA for approval. Should there be two? I haven't seen a response to that yet.

**Comment by codehag** [comment]
@michaelficarra I'll send the notes and the agenda to you. The documents were approved with the new license, there was no action to take on your end.

**Review by michaelficarra — APPROVED** [review]

**Review by littledan — APPROVED** [review]

**Comment by bakkot** [comment]
@codehag If that's so we want to update the [draft copyright](https://github.com/tc39/ecmarkup/blob/f07cabbff4958c78b3922cfbe4a2c2ef8577bd7d/boilerplate/draft-copyright.html) as well, right?

**Pull request merged**
