### PR TITLE
multipage: rewrite relative links

### PR DESCRIPTION
**Pull request by bakkot**
Includes version bump commit, so please **rebase**, not squash.

### CODE REVIEW

**Comment by michaelficarra** [comment]
I'd be more comfortable using the other properties like `protocol` and `pathname` instead of testing and slicing `href`.

**Comment by bakkot** [comment]
That's what I started with, but they don't work correctly in jsdom (at least in this version, which we [can't upgrade](https://github.com/jsdom/jsdom/issues/2968)).

**Comment by michaelficarra** [comment]
Okay, fine. Can we extract anything that touches `href` to an appropriately-named function which can be reimplemented in a better way in the future?

**Comment by bakkot** [comment]
Sure? I don't think it's an improvement, but done.

**Review by michaelficarra — APPROVED** [review]

**Pull request merged**
